pub const NightwaveChallenge = struct {
    name: []const u8,
    tier: ChallengeTier,
};

pub const ChallengeTier = enum {
    Daily,
    Weekly,
    EliteWeekly,
};

pub const NightwaveChallenges = enum {
    SeasonDailyPickUpMods,
    SeasonDailyVisitFeaturedDojo,
    SeasonDailyDeploySpecter,
    SeasonDailyKillEnemiesWithMelee,
    SeasonDailyKillEnemiesWithRadiation,
    SeasonDailyTwoForOne,
    SeasonDailyCompleteMission,
    SeasonDailyTransmuteMods,
    SeasonDailyKillEnemiesWithHeadshots,
    SeasonDailySolveCiphers,
    SeasonDailySlideKills,
    SeasonDailyPlayEmote,
    SeasonDailyPlaceMarker,
    SeasonDailyPickUpEnergy,
    SeasonDailyOpenLockers,
    SeasonDailyKillEnemiesWithFire,
    SeasonDailyKillEnemiesWithViral,
    SeasonDailyKillEnemiesWithSecondary,
    SeasonDailyKillEnemiesWithPoison,
    SeasonDailyKillEnemiesWithPrimary,
    SeasonDailyKillEnemiesWithMagnetic,
    SeasonDailyKillEnemiesWithGas,
    SeasonDailyKillEnemiesWithFreeze,
    SeasonDailyKillEnemiesWithFinishers,
    SeasonDailyKillEnemiesWithElectricity,
    SeasonDailyKillEnemiesWithCorrosive,
    SeasonDailyKillEnemiesWithBlast,
    SeasonDailyKillEnemiesWithAbilities,
    SeasonDailyPickUpMedallion,
    SeasonDailyKillEnemies,
    SeasonDailyInteractWithPet,
    SeasonDailyDeployGlyph,
    SeasonDailyDeployAirSupport,
    SeasonDailyCollectCredits,
    SeasonDailyCodexScan,
    SeasonDailyBulletJump,
    SeasonDailyAimGlide,
    SeasonDailyMercyKill,

    SeasonWeeklyLoyalty,
    SeasonWeeklyCompleteSpy,
    SeasonWeeklyRailjackHijackDestroyThree,
    SeasonWeeklyVenusBounties,
    SeasonWeeklyPlainsBounties,
    SeasonWeeklyUseForma,
    SeasonWeeklyUnlockRelics,
    SeasonWeeklyUnlockDragonVaults,
    SeasonWeeklySimarisScan,
    SeasonWeeklySanctuaryOnslaught,
    SeasonWeeklySabotageCaches,
    SeasonWeeklyPickUpRareMods,
    SeasonWeeklyPerfectAnimalCapture,
    SeasonWeeklyMineRareVenusResources,
    SeasonWeeklyMineRarePlainsResources,
    SeasonWeeklyKillThumper,
    SeasonWeeklyKillEximus,
    SeasonWeeklyKillEnemies,
    SeasonWeeklyGildModular,
    SeasonWeeklyCompleteVenusRace,
    SeasonWeeklyCompleteTreasures,
    SeasonWeeklyCompleteSyndicateMissions,
    SeasonWeeklyCompleteSortie,
    SeasonWeeklyCompleteSabotage,
    SeasonWeeklyCompleteRescue,
    SeasonWeeklyCompleteNightmareMissions,
    SeasonWeeklyCompleteMobileDefense,
    SeasonWeeklyCompleteKuva,
    SeasonWeeklyCompleteInvasionMissions,
    SeasonWeeklyCompleteExterminate,
    SeasonWeeklyCompleteDisruptionConduits,
    SeasonWeeklyCompleteClemMission,
    SeasonWeeklyCompleteCapture,
    SeasonWeeklyCompleteAssassination,
    SeasonWeeklyCatchRareVenusFish,
    SeasonWeeklyCatchRarePlainsFish,

    SeasonWeeklyPermanentCompleteMissions,
    SeasonWeeklyPermanentKillEximus,
    SeasonWeeklyPermanentKillEnemies,

    SeasonWeeklyHardRailjackMissions,
    SeasonWeeklyHardFriendsProfitTaker,
    SeasonWeeklyHardUnlockRelics,
    SeasonWeeklyHardLuaPuzzles,
    SeasonWeeklyHardKuvaSurvivalNoCapsules,
    SeasonWeeklyHardKillThumper,
    SeasonWeeklyHardKillSilverGroveSpecters,
    SeasonWeeklyHardKillRopalyst,
    SeasonWeeklyHardKillRopalolyst,
    SeasonWeeklyHardKillEximus,
    SeasonWeeklyHardKillEnemies,
    SeasonWeeklyHardIndexWinStreak,
    SeasonWeeklyHardFriendsSurvival,
    SeasonWeeklyHardFriendsDefense,
    SeasonWeeklyHardExterminateNoAlarm,
    SeasonWeeklyHardEliteSanctuaryOnslaught,
    SeasonWeeklyHardKillOrCaptureRainalyst,
    SeasonWeeklyHardCompleteSortie,
    SeasonWeeklyHardCompleteNightmareMissions,
    SeasonWeeklyHardTheManyMadeWhole,
    SeasonWeeklyHardRiseOfTheMachine,
    SeasonWeeklyHardCollectUniqueResources,

    UNKNOWN,
};

pub const Acolytes = enum {
    StrikerAcolyte,
    HeavyAcolyte,
    RogueAcolyte,
    AreaCasterAcolyte,
    ControlAcolyte,
    DuellistAcolyte,
};
